version: "3"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    volumes:
      - sql-data:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Strong_!_Password
      - ACCEPT_EULA="Y"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data

volumes:
  sql-data:
  azurite-data: